server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://root:PXOKggKgdmNHlTXx1KkT@containers-us-west-60.railway.app:7423/railway
    username: root
    password: PXOKggKgdmNHlTXx1KkT
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  image: /Users/kairb/Desktop/Fullstack projects/social_site/images
