server:
  port: 8080
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_db
    username: root
    password: password123
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    session:
      tracking-modes: cookie

project:
  image: /Users/kairb/Desktop/Fullstack projects/social_site/images

digital-ocean:
  access-key: ${DO_ACCESS_KEY}
  secret-key: ${DO_SECRET_KEY}

#this will stay the same as long as you do not clean and install it with maven**
