server:
  port: 8080
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto

spring:
  datasource:
    url: jdbc:mysql://root:PXOKggKgdmNHlTXx1KkT@containers-us-west-60.railway.app:7423/railway
    username: root
    password: PXOKggKgdmNHlTXx1KkT
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    session:
      tracking-modes: cookie
  mail:
    host: smtp.gmail.com
    port: 587
    username: test.email.forspring@gmail.com
    password: tqdjhucvwiwvanaa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

project:
  image: /Users/kairb/Desktop/Fullstack projects/social_site/images

digital-ocean:
  access-key: ${DO_ACCESS_KEY}
  secret-key: ${DO_SECRET_KEY}

#this will stay the same as long as you do not clean and install it with maven**
